# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:

  encoders:
    Symfony\Component\Security\Core\User\User: plaintext
    AdminBundle\Entity\Users: bcrypt

  providers:
    main:
      entity: { class: AdminBundle\Entity\Users, property: username }

  firewalls:
    # disables authentication for assets and the profiler, adapt it according to your needs
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false

    main:
      pattern:    ^/
      anonymous: ~
      form_login:
        login_path: /auth/login
        check_path: /auth/login
        default_target_path: /admin/
      logout:
        path:   /logout
        target: /auth/login
      security: false


  access_control:
#   require ROLE_ADMIN for /admin*
  - { path: ^/admin, roles: [ ROLE_ADMIN, ROLE_MANEGER] }